name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Check if directory exists
      run: |
       if [ ! -d "/home/user/DevOps" ]; then
       echo "Error: The directory to back up does not exist: /home/user/DevOps"
       exit 1
       fi

    - name: Run backup script
      run: |
       bash backup_script.sh /home/user/DevOps /home/user/Backup

    - name: Run tests
      run: |
        pytest
